//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imusik
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailLove
    {
        public int idDetailLove { get; set; }
        public int idLove { get; set; }
        public int idUser { get; set; }
        public Nullable<int> noLove { get; set; }
        public Nullable<int> littleLove { get; set; }
        public Nullable<int> love { get; set; }
        public Nullable<int> lotsofLove { get; set; }
        public Nullable<int> superLove { get; set; }
    
        public virtual Love Love1 { get; set; }
    }
}
