//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imusik
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Love
    {
        private object user;
        private IQueryable<object> loves;
        private double? sum;

        public int idLove { get; set; }
        public int idSong { get; set; }
        public int idUser { get; set; }
        public Nullable<int> noLove { get; set; }
        public Nullable<int> littleLove { get; set; }
        public Nullable<int> love1 { get; set; }
        public Nullable<int> superLove { get; set; }
        public Nullable<int> lotsofLove { get; set; }
    }
}
