//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imusik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Love
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Love()
        {
            this.DetailLoves = new HashSet<DetailLove>();
        }
    
        public int idLove { get; set; }
        public int idSong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailLove> DetailLoves { get; set; }
        public virtual Song Song { get; set; }
    }
}
